// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIBFu0EDIEXzBO1zJT0impG9yJHGmxb0Y',
    appId: '1:525581741124:web:92e6572c9b04edf040a011',
    messagingSenderId: '525581741124',
    projectId: 'expense-tracker-b9ad5',
    authDomain: 'expense-tracker-b9ad5.firebaseapp.com',
    storageBucket: 'expense-tracker-b9ad5.firebasestorage.app',
    measurementId: 'G-NKN2QZKTNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz5maIa72nIn1sOMI4T-mZQVqf_aYuUCg',
    appId: '1:525581741124:android:f0874f6b6adb727840a011',
    messagingSenderId: '525581741124',
    projectId: 'expense-tracker-b9ad5',
    storageBucket: 'expense-tracker-b9ad5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOcJVJH7wwMHe57FR1K32kKSV1df8Qlro',
    appId: '1:525581741124:ios:8e44b7214c5e643940a011',
    messagingSenderId: '525581741124',
    projectId: 'expense-tracker-b9ad5',
    storageBucket: 'expense-tracker-b9ad5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOcJVJH7wwMHe57FR1K32kKSV1df8Qlro',
    appId: '1:525581741124:ios:8e44b7214c5e643940a011',
    messagingSenderId: '525581741124',
    projectId: 'expense-tracker-b9ad5',
    storageBucket: 'expense-tracker-b9ad5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIBFu0EDIEXzBO1zJT0impG9yJHGmxb0Y',
    appId: '1:525581741124:web:c2c25d51f1c3c19d40a011',
    messagingSenderId: '525581741124',
    projectId: 'expense-tracker-b9ad5',
    authDomain: 'expense-tracker-b9ad5.firebaseapp.com',
    storageBucket: 'expense-tracker-b9ad5.firebasestorage.app',
    measurementId: 'G-JYY675GNC6',
  );
}
